site_name: Open 3D Engine at ROSCon 2023
site_url: https://robotecai.github.io/roscon2023-landing-page/
repo_url: https://github.com/RobotecAI/ROSCon2023Demo
edit_uri: https://github.com/RobotecAI/roscon2023-landing-page
docs_dir: docs
copyright: Copyright &copy; 2023 Robotec.ai

